<?php
/**
 * ConditionalOperator
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: support@ziqni.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\com.ziqni.admin.sdk.model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ConditionalOperator Class Doc Comment
 *
 * @category Class
 * @description Available actions for competition status
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConditionalOperator
{
    /**
     * Possible values of this enum
     */
    public const EQUALS = 'Equals';

    public const GREATER_THAN = 'GreaterThan';

    public const GREATER_THAN_EQUALS = 'GreaterThanEquals';

    public const LESS_THAN = 'LessThan';

    public const LESS_THAN_EQUALS = 'LessThanEquals';

    public const BETWEEN = 'Between';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EQUALS,
            self::GREATER_THAN,
            self::GREATER_THAN_EQUALS,
            self::LESS_THAN,
            self::LESS_THAN_EQUALS,
            self::BETWEEN
        ];
    }
}


