<?php
/**
 * UpdateCompetitionRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: support@ziqni.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\com.ziqni.admin.sdk.model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * UpdateCompetitionRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UpdateCompetitionRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UpdateCompetitionRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'custom_fields' => 'array<string,mixed>',
        'tags' => 'string[]',
        'metadata' => 'array<string,string>',
        'competition_type' => '\OpenAPI\Client\com.ziqni.admin.sdk.model\CompetitionType',
        'number_of_rounds' => 'int',
        'number_of_group_stages' => 'int',
        'name' => 'string',
        'description' => 'string',
        'terms_and_conditions' => 'string',
        'entrant_member_type' => 'string',
        'max_number_of_entrants' => 'int',
        'min_number_of_entrants' => 'int',
        'scheduled_start_date' => '\DateTime',
        'scheduled_end_date' => '\DateTime',
        'constraints' => 'string[]',
        'add_constraints' => 'string[]',
        'remove_constraints' => 'string[]',
        'product_ids' => 'string[]',
        'create_contests' => '\OpenAPI\Client\com.ziqni.admin.sdk.model\CreateContestForCompetitionRequest',
        'update_contests' => '\OpenAPI\Client\com.ziqni.admin.sdk.model\UpdateContestRequest',
        'entrant_member_tags_filter' => '\OpenAPI\Client\com.ziqni.admin.sdk.model\DependantOn',
        'product_tags_filter' => '\OpenAPI\Client\com.ziqni.admin.sdk.model\DependantOn',
        'icon' => 'string',
        'banner' => 'string',
        'banner_low_resolution' => 'string',
        'banner_high_resolution' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'custom_fields' => null,
        'tags' => null,
        'metadata' => null,
        'competition_type' => null,
        'number_of_rounds' => 'int32',
        'number_of_group_stages' => null,
        'name' => null,
        'description' => null,
        'terms_and_conditions' => null,
        'entrant_member_type' => null,
        'max_number_of_entrants' => 'int32',
        'min_number_of_entrants' => 'int32',
        'scheduled_start_date' => 'date-time',
        'scheduled_end_date' => 'date-time',
        'constraints' => null,
        'add_constraints' => null,
        'remove_constraints' => null,
        'product_ids' => null,
        'create_contests' => null,
        'update_contests' => null,
        'entrant_member_tags_filter' => null,
        'product_tags_filter' => null,
        'icon' => null,
        'banner' => null,
        'banner_low_resolution' => null,
        'banner_high_resolution' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'custom_fields' => false,
		'tags' => false,
		'metadata' => false,
		'competition_type' => false,
		'number_of_rounds' => false,
		'number_of_group_stages' => false,
		'name' => false,
		'description' => false,
		'terms_and_conditions' => false,
		'entrant_member_type' => false,
		'max_number_of_entrants' => false,
		'min_number_of_entrants' => false,
		'scheduled_start_date' => false,
		'scheduled_end_date' => false,
		'constraints' => false,
		'add_constraints' => false,
		'remove_constraints' => false,
		'product_ids' => false,
		'create_contests' => false,
		'update_contests' => false,
		'entrant_member_tags_filter' => false,
		'product_tags_filter' => false,
		'icon' => false,
		'banner' => false,
		'banner_low_resolution' => false,
		'banner_high_resolution' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'custom_fields' => 'customFields',
        'tags' => 'tags',
        'metadata' => 'metadata',
        'competition_type' => 'competitionType',
        'number_of_rounds' => 'numberOfRounds',
        'number_of_group_stages' => 'numberOfGroupStages',
        'name' => 'name',
        'description' => 'description',
        'terms_and_conditions' => 'termsAndConditions',
        'entrant_member_type' => 'entrantMemberType',
        'max_number_of_entrants' => 'maxNumberOfEntrants',
        'min_number_of_entrants' => 'minNumberOfEntrants',
        'scheduled_start_date' => 'scheduledStartDate',
        'scheduled_end_date' => 'scheduledEndDate',
        'constraints' => 'constraints',
        'add_constraints' => 'addConstraints',
        'remove_constraints' => 'removeConstraints',
        'product_ids' => 'productIds',
        'create_contests' => 'createContests',
        'update_contests' => 'updateContests',
        'entrant_member_tags_filter' => 'entrantMemberTagsFilter',
        'product_tags_filter' => 'productTagsFilter',
        'icon' => 'icon',
        'banner' => 'banner',
        'banner_low_resolution' => 'bannerLowResolution',
        'banner_high_resolution' => 'bannerHighResolution'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'custom_fields' => 'setCustomFields',
        'tags' => 'setTags',
        'metadata' => 'setMetadata',
        'competition_type' => 'setCompetitionType',
        'number_of_rounds' => 'setNumberOfRounds',
        'number_of_group_stages' => 'setNumberOfGroupStages',
        'name' => 'setName',
        'description' => 'setDescription',
        'terms_and_conditions' => 'setTermsAndConditions',
        'entrant_member_type' => 'setEntrantMemberType',
        'max_number_of_entrants' => 'setMaxNumberOfEntrants',
        'min_number_of_entrants' => 'setMinNumberOfEntrants',
        'scheduled_start_date' => 'setScheduledStartDate',
        'scheduled_end_date' => 'setScheduledEndDate',
        'constraints' => 'setConstraints',
        'add_constraints' => 'setAddConstraints',
        'remove_constraints' => 'setRemoveConstraints',
        'product_ids' => 'setProductIds',
        'create_contests' => 'setCreateContests',
        'update_contests' => 'setUpdateContests',
        'entrant_member_tags_filter' => 'setEntrantMemberTagsFilter',
        'product_tags_filter' => 'setProductTagsFilter',
        'icon' => 'setIcon',
        'banner' => 'setBanner',
        'banner_low_resolution' => 'setBannerLowResolution',
        'banner_high_resolution' => 'setBannerHighResolution'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'custom_fields' => 'getCustomFields',
        'tags' => 'getTags',
        'metadata' => 'getMetadata',
        'competition_type' => 'getCompetitionType',
        'number_of_rounds' => 'getNumberOfRounds',
        'number_of_group_stages' => 'getNumberOfGroupStages',
        'name' => 'getName',
        'description' => 'getDescription',
        'terms_and_conditions' => 'getTermsAndConditions',
        'entrant_member_type' => 'getEntrantMemberType',
        'max_number_of_entrants' => 'getMaxNumberOfEntrants',
        'min_number_of_entrants' => 'getMinNumberOfEntrants',
        'scheduled_start_date' => 'getScheduledStartDate',
        'scheduled_end_date' => 'getScheduledEndDate',
        'constraints' => 'getConstraints',
        'add_constraints' => 'getAddConstraints',
        'remove_constraints' => 'getRemoveConstraints',
        'product_ids' => 'getProductIds',
        'create_contests' => 'getCreateContests',
        'update_contests' => 'getUpdateContests',
        'entrant_member_tags_filter' => 'getEntrantMemberTagsFilter',
        'product_tags_filter' => 'getProductTagsFilter',
        'icon' => 'getIcon',
        'banner' => 'getBanner',
        'banner_low_resolution' => 'getBannerLowResolution',
        'banner_high_resolution' => 'getBannerHighResolution'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('custom_fields', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('competition_type', $data ?? [], null);
        $this->setIfExists('number_of_rounds', $data ?? [], null);
        $this->setIfExists('number_of_group_stages', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('terms_and_conditions', $data ?? [], null);
        $this->setIfExists('entrant_member_type', $data ?? [], null);
        $this->setIfExists('max_number_of_entrants', $data ?? [], null);
        $this->setIfExists('min_number_of_entrants', $data ?? [], null);
        $this->setIfExists('scheduled_start_date', $data ?? [], null);
        $this->setIfExists('scheduled_end_date', $data ?? [], null);
        $this->setIfExists('constraints', $data ?? [], null);
        $this->setIfExists('add_constraints', $data ?? [], null);
        $this->setIfExists('remove_constraints', $data ?? [], null);
        $this->setIfExists('product_ids', $data ?? [], null);
        $this->setIfExists('create_contests', $data ?? [], null);
        $this->setIfExists('update_contests', $data ?? [], null);
        $this->setIfExists('entrant_member_tags_filter', $data ?? [], null);
        $this->setIfExists('product_tags_filter', $data ?? [], null);
        $this->setIfExists('icon', $data ?? [], null);
        $this->setIfExists('banner', $data ?? [], null);
        $this->setIfExists('banner_low_resolution', $data ?? [], null);
        $this->setIfExists('banner_high_resolution', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id A unique system generated identifier
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return array<string,mixed>|null
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param array<string,mixed>|null $custom_fields A list of id's used to add cutom fields
     *
     * @return self
     */
    public function setCustomFields($custom_fields)
    {
        if (is_null($custom_fields)) {
            throw new \InvalidArgumentException('non-nullable custom_fields cannot be null');
        }
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags A list of id's used to tag models
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,string>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,string>|null $metadata metadata
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets competition_type
     *
     * @return \OpenAPI\Client\com.ziqni.admin.sdk.model\CompetitionType|null
     */
    public function getCompetitionType()
    {
        return $this->container['competition_type'];
    }

    /**
     * Sets competition_type
     *
     * @param \OpenAPI\Client\com.ziqni.admin.sdk.model\CompetitionType|null $competition_type competition_type
     *
     * @return self
     */
    public function setCompetitionType($competition_type)
    {
        if (is_null($competition_type)) {
            throw new \InvalidArgumentException('non-nullable competition_type cannot be null');
        }
        $this->container['competition_type'] = $competition_type;

        return $this;
    }

    /**
     * Gets number_of_rounds
     *
     * @return int|null
     */
    public function getNumberOfRounds()
    {
        return $this->container['number_of_rounds'];
    }

    /**
     * Sets number_of_rounds
     *
     * @param int|null $number_of_rounds Number of rounds to be played in a competition
     *
     * @return self
     */
    public function setNumberOfRounds($number_of_rounds)
    {
        if (is_null($number_of_rounds)) {
            throw new \InvalidArgumentException('non-nullable number_of_rounds cannot be null');
        }
        $this->container['number_of_rounds'] = $number_of_rounds;

        return $this;
    }

    /**
     * Gets number_of_group_stages
     *
     * @return int|null
     */
    public function getNumberOfGroupStages()
    {
        return $this->container['number_of_group_stages'];
    }

    /**
     * Sets number_of_group_stages
     *
     * @param int|null $number_of_group_stages Number of group stages
     *
     * @return self
     */
    public function setNumberOfGroupStages($number_of_group_stages)
    {
        if (is_null($number_of_group_stages)) {
            throw new \InvalidArgumentException('non-nullable number_of_group_stages cannot be null');
        }
        $this->container['number_of_group_stages'] = $number_of_group_stages;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name A name or a name of a competition. Can be translated
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Description of the competition. Can be translated
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets terms_and_conditions
     *
     * @return string|null
     */
    public function getTermsAndConditions()
    {
        return $this->container['terms_and_conditions'];
    }

    /**
     * Sets terms_and_conditions
     *
     * @param string|null $terms_and_conditions Terms and conditions of a competition. Can be translated
     *
     * @return self
     */
    public function setTermsAndConditions($terms_and_conditions)
    {
        if (is_null($terms_and_conditions)) {
            throw new \InvalidArgumentException('non-nullable terms_and_conditions cannot be null');
        }
        $this->container['terms_and_conditions'] = $terms_and_conditions;

        return $this;
    }

    /**
     * Gets entrant_member_type
     *
     * @return string|null
     */
    public function getEntrantMemberType()
    {
        return $this->container['entrant_member_type'];
    }

    /**
     * Sets entrant_member_type
     *
     * @param string|null $entrant_member_type entrant_member_type
     *
     * @return self
     */
    public function setEntrantMemberType($entrant_member_type)
    {
        if (is_null($entrant_member_type)) {
            throw new \InvalidArgumentException('non-nullable entrant_member_type cannot be null');
        }
        $this->container['entrant_member_type'] = $entrant_member_type;

        return $this;
    }

    /**
     * Gets max_number_of_entrants
     *
     * @return int|null
     */
    public function getMaxNumberOfEntrants()
    {
        return $this->container['max_number_of_entrants'];
    }

    /**
     * Sets max_number_of_entrants
     *
     * @param int|null $max_number_of_entrants Maximum number of partiipants allowed in a competition
     *
     * @return self
     */
    public function setMaxNumberOfEntrants($max_number_of_entrants)
    {
        if (is_null($max_number_of_entrants)) {
            throw new \InvalidArgumentException('non-nullable max_number_of_entrants cannot be null');
        }
        $this->container['max_number_of_entrants'] = $max_number_of_entrants;

        return $this;
    }

    /**
     * Gets min_number_of_entrants
     *
     * @return int|null
     */
    public function getMinNumberOfEntrants()
    {
        return $this->container['min_number_of_entrants'];
    }

    /**
     * Sets min_number_of_entrants
     *
     * @param int|null $min_number_of_entrants Maximum number of partiipants allowed in a competition
     *
     * @return self
     */
    public function setMinNumberOfEntrants($min_number_of_entrants)
    {
        if (is_null($min_number_of_entrants)) {
            throw new \InvalidArgumentException('non-nullable min_number_of_entrants cannot be null');
        }
        $this->container['min_number_of_entrants'] = $min_number_of_entrants;

        return $this;
    }

    /**
     * Gets scheduled_start_date
     *
     * @return \DateTime|null
     */
    public function getScheduledStartDate()
    {
        return $this->container['scheduled_start_date'];
    }

    /**
     * Sets scheduled_start_date
     *
     * @param \DateTime|null $scheduled_start_date ISO8601 timestamp for when a Competition should start. All records are stored in UTC time zone
     *
     * @return self
     */
    public function setScheduledStartDate($scheduled_start_date)
    {
        if (is_null($scheduled_start_date)) {
            throw new \InvalidArgumentException('non-nullable scheduled_start_date cannot be null');
        }
        $this->container['scheduled_start_date'] = $scheduled_start_date;

        return $this;
    }

    /**
     * Gets scheduled_end_date
     *
     * @return \DateTime|null
     */
    public function getScheduledEndDate()
    {
        return $this->container['scheduled_end_date'];
    }

    /**
     * Sets scheduled_end_date
     *
     * @param \DateTime|null $scheduled_end_date ISO8601 timestamp for when a Competition should end. All records are stored in UTC time zone
     *
     * @return self
     */
    public function setScheduledEndDate($scheduled_end_date)
    {
        if (is_null($scheduled_end_date)) {
            throw new \InvalidArgumentException('non-nullable scheduled_end_date cannot be null');
        }
        $this->container['scheduled_end_date'] = $scheduled_end_date;

        return $this;
    }

    /**
     * Gets constraints
     *
     * @return string[]|null
     * @deprecated
     */
    public function getConstraints()
    {
        return $this->container['constraints'];
    }

    /**
     * Sets constraints
     *
     * @param string[]|null $constraints Additional constraints
     *
     * @return self
     * @deprecated
     */
    public function setConstraints($constraints)
    {
        if (is_null($constraints)) {
            throw new \InvalidArgumentException('non-nullable constraints cannot be null');
        }
        $this->container['constraints'] = $constraints;

        return $this;
    }

    /**
     * Gets add_constraints
     *
     * @return string[]|null
     */
    public function getAddConstraints()
    {
        return $this->container['add_constraints'];
    }

    /**
     * Sets add_constraints
     *
     * @param string[]|null $add_constraints Additional constraints
     *
     * @return self
     */
    public function setAddConstraints($add_constraints)
    {
        if (is_null($add_constraints)) {
            throw new \InvalidArgumentException('non-nullable add_constraints cannot be null');
        }
        $this->container['add_constraints'] = $add_constraints;

        return $this;
    }

    /**
     * Gets remove_constraints
     *
     * @return string[]|null
     */
    public function getRemoveConstraints()
    {
        return $this->container['remove_constraints'];
    }

    /**
     * Sets remove_constraints
     *
     * @param string[]|null $remove_constraints Additional constraints
     *
     * @return self
     */
    public function setRemoveConstraints($remove_constraints)
    {
        if (is_null($remove_constraints)) {
            throw new \InvalidArgumentException('non-nullable remove_constraints cannot be null');
        }
        $this->container['remove_constraints'] = $remove_constraints;

        return $this;
    }

    /**
     * Gets product_ids
     *
     * @return string[]|null
     */
    public function getProductIds()
    {
        return $this->container['product_ids'];
    }

    /**
     * Sets product_ids
     *
     * @param string[]|null $product_ids 
     *
     * @return self
     */
    public function setProductIds($product_ids)
    {
        if (is_null($product_ids)) {
            throw new \InvalidArgumentException('non-nullable product_ids cannot be null');
        }
        $this->container['product_ids'] = $product_ids;

        return $this;
    }

    /**
     * Gets create_contests
     *
     * @return \OpenAPI\Client\com.ziqni.admin.sdk.model\CreateContestForCompetitionRequest|null
     */
    public function getCreateContests()
    {
        return $this->container['create_contests'];
    }

    /**
     * Sets create_contests
     *
     * @param \OpenAPI\Client\com.ziqni.admin.sdk.model\CreateContestForCompetitionRequest|null $create_contests create_contests
     *
     * @return self
     */
    public function setCreateContests($create_contests)
    {
        if (is_null($create_contests)) {
            throw new \InvalidArgumentException('non-nullable create_contests cannot be null');
        }
        $this->container['create_contests'] = $create_contests;

        return $this;
    }

    /**
     * Gets update_contests
     *
     * @return \OpenAPI\Client\com.ziqni.admin.sdk.model\UpdateContestRequest|null
     */
    public function getUpdateContests()
    {
        return $this->container['update_contests'];
    }

    /**
     * Sets update_contests
     *
     * @param \OpenAPI\Client\com.ziqni.admin.sdk.model\UpdateContestRequest|null $update_contests update_contests
     *
     * @return self
     */
    public function setUpdateContests($update_contests)
    {
        if (is_null($update_contests)) {
            throw new \InvalidArgumentException('non-nullable update_contests cannot be null');
        }
        $this->container['update_contests'] = $update_contests;

        return $this;
    }

    /**
     * Gets entrant_member_tags_filter
     *
     * @return \OpenAPI\Client\com.ziqni.admin.sdk.model\DependantOn|null
     */
    public function getEntrantMemberTagsFilter()
    {
        return $this->container['entrant_member_tags_filter'];
    }

    /**
     * Sets entrant_member_tags_filter
     *
     * @param \OpenAPI\Client\com.ziqni.admin.sdk.model\DependantOn|null $entrant_member_tags_filter entrant_member_tags_filter
     *
     * @return self
     */
    public function setEntrantMemberTagsFilter($entrant_member_tags_filter)
    {
        if (is_null($entrant_member_tags_filter)) {
            throw new \InvalidArgumentException('non-nullable entrant_member_tags_filter cannot be null');
        }
        $this->container['entrant_member_tags_filter'] = $entrant_member_tags_filter;

        return $this;
    }

    /**
     * Gets product_tags_filter
     *
     * @return \OpenAPI\Client\com.ziqni.admin.sdk.model\DependantOn|null
     */
    public function getProductTagsFilter()
    {
        return $this->container['product_tags_filter'];
    }

    /**
     * Sets product_tags_filter
     *
     * @param \OpenAPI\Client\com.ziqni.admin.sdk.model\DependantOn|null $product_tags_filter product_tags_filter
     *
     * @return self
     */
    public function setProductTagsFilter($product_tags_filter)
    {
        if (is_null($product_tags_filter)) {
            throw new \InvalidArgumentException('non-nullable product_tags_filter cannot be null');
        }
        $this->container['product_tags_filter'] = $product_tags_filter;

        return $this;
    }

    /**
     * Gets icon
     *
     * @return string|null
     */
    public function getIcon()
    {
        return $this->container['icon'];
    }

    /**
     * Sets icon
     *
     * @param string|null $icon Link to the icon
     *
     * @return self
     */
    public function setIcon($icon)
    {
        if (is_null($icon)) {
            throw new \InvalidArgumentException('non-nullable icon cannot be null');
        }
        $this->container['icon'] = $icon;

        return $this;
    }

    /**
     * Gets banner
     *
     * @return string|null
     */
    public function getBanner()
    {
        return $this->container['banner'];
    }

    /**
     * Sets banner
     *
     * @param string|null $banner Link to the banner
     *
     * @return self
     */
    public function setBanner($banner)
    {
        if (is_null($banner)) {
            throw new \InvalidArgumentException('non-nullable banner cannot be null');
        }
        $this->container['banner'] = $banner;

        return $this;
    }

    /**
     * Gets banner_low_resolution
     *
     * @return string|null
     */
    public function getBannerLowResolution()
    {
        return $this->container['banner_low_resolution'];
    }

    /**
     * Sets banner_low_resolution
     *
     * @param string|null $banner_low_resolution Link to the bannerLowResolution
     *
     * @return self
     */
    public function setBannerLowResolution($banner_low_resolution)
    {
        if (is_null($banner_low_resolution)) {
            throw new \InvalidArgumentException('non-nullable banner_low_resolution cannot be null');
        }
        $this->container['banner_low_resolution'] = $banner_low_resolution;

        return $this;
    }

    /**
     * Gets banner_high_resolution
     *
     * @return string|null
     */
    public function getBannerHighResolution()
    {
        return $this->container['banner_high_resolution'];
    }

    /**
     * Sets banner_high_resolution
     *
     * @param string|null $banner_high_resolution Link to the bannerHighResolution
     *
     * @return self
     */
    public function setBannerHighResolution($banner_high_resolution)
    {
        if (is_null($banner_high_resolution)) {
            throw new \InvalidArgumentException('non-nullable banner_high_resolution cannot be null');
        }
        $this->container['banner_high_resolution'] = $banner_high_resolution;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


